Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::value<AW::E2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86-64-gp2'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing key pair to enable ssh to an instance
    ConstraintDescription: Must be an existing KeyPair.
  SSHandWebLocation:
    Type: String
    Description: The Ip address range that can be sed to SSh to the Ec2 instances
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x. Default is 0.0.0.0/0 and is less safe.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: "t2.micro"
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref SessionManagerInstanceProfile
      SecurityGroups: 
        - !Ref InstanceSecurityGroup
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22 and 80
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: '22'
         ToPort: '22'
         CidrIp: !Ref SSHandWebLocation
       - IpProtocol: tcp
         FromPort: '80'
         ToPort: '80'
         CidrIp: !Ref SSHandWebLocation

  SessionManagerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWmazonSSMManagedInstanceCore"

  SessionManagerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles: 
        - !Ref SessionManagerRole

Outputs:
  InstanceId:
    Description: Instance Id of the newly created EC2 Instance
    Value: !Ref EC2Instance

  AZ:
    Description: Availability zone of the newly created EC2 Instance
    Value: !GetAtt
      - EC2Instance
      - AvailabilityZone

  PublicDNS:
    Description: PublicDnsName of the newly created EC2 Instance
    Value: !GetAtt
      - EC2Instance
      - PublicDnsName

  PublicIp:
    Description: Public IP address of the newly created EC2 Instance
    Value: !GetAtt
    - EC2Instance
    - PublicIp